<?php
namespace Gutshot\Controllers;

use Phalcon\Tag;
use Phalcon\Mvc\Model\Criteria;
use Phalcon\Paginator\Adapter\Model as Paginator;
use Gutshot\Forms\TourneysForm;
use Gutshot\Models\BalanceHistories;
use Gutshot\Models\Cashouts;
use Gutshot\Models\Deposits;
use Gutshot\Models\HandHistories;
use Gutshot\Models\Honors;
use Gutshot\Models\SuccessLogins;
use Gutshot\Models\Support;
use Gutshot\Models\Tourneys;
use Gutshot\Models\PasswordChanges;
use Gutshot\Models\Transfers;
use Gutshot\Models\Users;

/**
 * Gutshot\Controllers\TournamentsController
 * CRUD to manage tournaments
 */
class SystemController extends ControllerBase
{

    public function initialize()
    {
        $this->view->setTemplateBefore('private');
    }

    /**
     *
     */
    public function userAction()
    {
        if ($this->request->isPost()) {

            // Get User
            $user = Users::findFirstById($this->request->getPost('usersId'));

            if ($user) {
                $usersId = $user->id;
                $usersPlayer = $user->player;
                if (empty($date = $this->request->getPost('date')))
                    $dateCondition = "";
                else
                    $dateCondition = " AND createdAt > " . strtotime($date);

                $parameters = array(
                    "conditions" => "usersId = " . $usersId . $dateCondition,
                    "order" => "createdAt DESC",
                );
                //Related Models
                $this->view->successLogins = $user->getRelated('successLogins', $parameters);
                $this->view->passwordChanges = $user->getRelated('passwordChanges', $parameters);
                $this->view->resetPasswords = $user->getRelated('resetPasswords', $parameters);
                $this->view->invitations = $user->getRelated('invitations', $parameters);

                $deposits = Deposits::find($parameters);
                $cashouts = Cashouts::find($parameters);
                $honors = Honors::find($parameters);
                $supports = Support::find($parameters);
                $this->view->deposits = $deposits;
                $this->view->cashouts = $cashouts;
                $this->view->honors = $honors;
                $this->view->supports = $supports;

                $parameters = array(
                    "conditions" => "player = '" . $usersPlayer . "'" . $dateCondition,
                    "order" => "createdAt DESC",
                );
                $handhistories = HandHistories::find($parameters);
                $balancesDetails = BalanceHistories::find($parameters);
                $this->view->handhistories = $handhistories;
                $this->view->balancesDetails = $balancesDetails;

                $parameters = array(
                    "conditions" => "fromId =" . $usersId . $dateCondition . " OR toId =" . $usersId . $dateCondition,
                    "order" => "createdAt DESC",
                );
                $transfers = Transfers::find($parameters);
                $this->view->transfers = $transfers;

                $params = array("Command" => "AccountsGet",
                    "Player" => $usersPlayer,
                );
                $api = $this->getDI()->getApi()->poker($params);
                $this->view->AccountsGet = $api;

                $this->view->userDetails = $user;
            }
        }
        // Pass all
        $this->view->users = Users::find();
    }

    public function handValueAction()
    {
        $hand_values = array(
            'Royal flush, Ace high +KQJT',
            'a Straight Flush, Nine to King',
            'a Straight Flush, Eight to Queen',
            'a Straight Flush, Seven to Jack',
            'a Straight Flush, Six to Ten',
            'a Straight Flush, Five to Nine',
            'a Straight Flush, Four to Eight',
            'a Straight Flush, Three to Seven',
            'a Straight Flush, Two to Six',
            'a Straight Flush, Ace to Five',
            'Four of a Kind, Aces +K',
            'Four of a Kind, Aces +Q',
            'Four of a Kind, Aces +J',
            'Four of a Kind, Aces +T',
            'Four of a Kind, Aces +9',
            'Four of a Kind, Aces +8',
            'Four of a Kind, Aces +7',
            'Four of a Kind, Aces +6',
            'Four of a Kind, Aces +5',
            'Four of a Kind, Aces +4',
            'Four of a Kind, Aces +3',
            'Four of a Kind, Aces +2',
            'Four of a Kind, Kings +A',
            'Four of a Kind, Kings +Q',
            'Four of a Kind, Kings +J',
            'Four of a Kind, Kings +T',
            'Four of a Kind, Kings +9',
            'Four of a Kind, Kings +8',
            'Four of a Kind, Kings +7',
            'Four of a Kind, Kings +6',
            'Four of a Kind, Kings +5',
            'Four of a Kind, Kings +4',
            'Four of a Kind, Kings +3',
            'Four of a Kind, Kings +2',
            'Four of a Kind, Queens +A',
            'Four of a Kind, Queens +K',
            'Four of a Kind, Queens +J',
            'Four of a Kind, Queens +T',
            'Four of a Kind, Queens +9',
            'Four of a Kind, Queens +8',
            'Four of a Kind, Queens +7',
            'Four of a Kind, Queens +6',
            'Four of a Kind, Queens +5',
            'Four of a Kind, Queens +4',
            'Four of a Kind, Queens +3',
            'Four of a Kind, Queens +2',
            'Four of a Kind, Jacks +A',
            'Four of a Kind, Jacks +K',
            'Four of a Kind, Jacks +Q',
            'Four of a Kind, Jacks +T',
            'Four of a Kind, Jacks +9',
            'Four of a Kind, Jacks +8',
            'Four of a Kind, Jacks +7',
            'Four of a Kind, Jacks +6',
            'Four of a Kind, Jacks +5',
            'Four of a Kind, Jacks +4',
            'Four of a Kind, Jacks +3',
            'Four of a Kind, Jacks +2',
            'Four of a Kind, Tens +A',
            'Four of a Kind, Tens +K',
            'Four of a Kind, Tens +Q',
            'Four of a Kind, Tens +J',
            'Four of a Kind, Tens +9',
            'Four of a Kind, Tens +8',
            'Four of a Kind, Tens +7',
            'Four of a Kind, Tens +6',
            'Four of a Kind, Tens +5',
            'Four of a Kind, Tens +4',
            'Four of a Kind, Tens +3',
            'Four of a Kind, Tens +2',
            'Four of a Kind, Nines +A',
            'Four of a Kind, Nines +K',
            'Four of a Kind, Nines +Q',
            'Four of a Kind, Nines +J',
            'Four of a Kind, Nines +T',
            'Four of a Kind, Nines +8',
            'Four of a Kind, Nines +7',
            'Four of a Kind, Nines +6',
            'Four of a Kind, Nines +5',
            'Four of a Kind, Nines +4',
            'Four of a Kind, Nines +3',
            'Four of a Kind, Nines +2',
            'Four of a Kind, Eights +A',
            'Four of a Kind, Eights +K',
            'Four of a Kind, Eights +Q',
            'Four of a Kind, Eights +J',
            'Four of a Kind, Eights +T',
            'Four of a Kind, Eights +9',
            'Four of a Kind, Eights +7',
            'Four of a Kind, Eights +6',
            'Four of a Kind, Eights +5',
            'Four of a Kind, Eights +4',
            'Four of a Kind, Eights +3',
            'Four of a Kind, Eights +2',
            'Four of a Kind, Sevens +A',
            'Four of a Kind, Sevens +K',
            'Four of a Kind, Sevens +Q',
            'Four of a Kind, Sevens +J',
            'Four of a Kind, Sevens +T',
            'Four of a Kind, Sevens +9',
            'Four of a Kind, Sevens +8',
            'Four of a Kind, Sevens +6',
            'Four of a Kind, Sevens +5',
            'Four of a Kind, Sevens +4',
            'Four of a Kind, Sevens +3',
            'Four of a Kind, Sevens +2',
            'Four of a Kind, Sixes +A',
            'Four of a Kind, Sixes +K',
            'Four of a Kind, Sixes +Q',
            'Four of a Kind, Sixes +J',
            'Four of a Kind, Sixes +T',
            'Four of a Kind, Sixes +9',
            'Four of a Kind, Sixes +8',
            'Four of a Kind, Sixes +7',
            'Four of a Kind, Sixes +5',
            'Four of a Kind, Sixes +4',
            'Four of a Kind, Sixes +3',
            'Four of a Kind, Sixes +2',
            'Four of a Kind, Fives +A',
            'Four of a Kind, Fives +K',
            'Four of a Kind, Fives +Q',
            'Four of a Kind, Fives +J',
            'Four of a Kind, Fives +T',
            'Four of a Kind, Fives +9',
            'Four of a Kind, Fives +8',
            'Four of a Kind, Fives +7',
            'Four of a Kind, Fives +6',
            'Four of a Kind, Fives +4',
            'Four of a Kind, Fives +3',
            'Four of a Kind, Fives +2',
            'Four of a Kind, Fours +A',
            'Four of a Kind, Fours +K',
            'Four of a Kind, Fours +Q',
            'Four of a Kind, Fours +J',
            'Four of a Kind, Fours +T',
            'Four of a Kind, Fours +9',
            'Four of a Kind, Fours +8',
            'Four of a Kind, Fours +7',
            'Four of a Kind, Fours +6',
            'Four of a Kind, Fours +5',
            'Four of a Kind, Fours +3',
            'Four of a Kind, Fours +2',
            'Four of a Kind, Threes +A',
            'Four of a Kind, Threes +K',
            'Four of a Kind, Threes +Q',
            'Four of a Kind, Threes +J',
            'Four of a Kind, Threes +T',
            'Four of a Kind, Threes +9',
            'Four of a Kind, Threes +8',
            'Four of a Kind, Threes +7',
            'Four of a Kind, Threes +6',
            'Four of a Kind, Threes +5',
            'Four of a Kind, Threes +4',
            'Four of a Kind, Threes +2',
            'Four of a Kind, Deuces +A',
            'Four of a Kind, Deuces +K',
            'Four of a Kind, Deuces +Q',
            'Four of a Kind, Deuces +J',
            'Four of a Kind, Deuces +T',
            'Four of a Kind, Deuces +9',
            'Four of a Kind, Deuces +8',
            'Four of a Kind, Deuces +7',
            'Four of a Kind, Deuces +6',
            'Four of a Kind, Deuces +5',
            'Four of a Kind, Deuces +4',
            'Four of a Kind, Deuces +3',
            'a Full House, Aces full of Kings',
            'a Full House, Aces full of Queens',
            'a Full House, Aces full of Jacks',
            'a Full House, Aces full of Tens',
            'a Full House, Aces full of Nines',
            'a Full House, Aces full of Eights',
            'a Full House, Aces full of Sevens',
            'a Full House, Aces full of Sixes',
            'a Full House, Aces full of Fives',
            'a Full House, Aces full of Fours',
            'a Full House, Aces full of Threes',
            'a Full House, Aces full of Deuces',
            'a Full House, Kings full of Aces',
            'a Full House, Kings full of Queens',
            'a Full House, Kings full of Jacks',
            'a Full House, Kings full of Tens',
            'a Full House, Kings full of Nines',
            'a Full House, Kings full of Eights',
            'a Full House, Kings full of Sevens',
            'a Full House, Kings full of Sixes',
            'a Full House, Kings full of Fives',
            'a Full House, Kings full of Fours',
            'a Full House, Kings full of Threes',
            'a Full House, Kings full of Deuces',
            'a Full House, Queens full of Aces',
            'a Full House, Queens full of Kings',
            'a Full House, Queens full of Jacks',
            'a Full House, Queens full of Tens',
            'a Full House, Queens full of Nines',
            'a Full House, Queens full of Eights',
            'a Full House, Queens full of Sevens',
            'a Full House, Queens full of Sixes',
            'a Full House, Queens full of Fives',
            'a Full House, Queens full of Fours',
            'a Full House, Queens full of Threes',
            'a Full House, Queens full of Deuces',
            'a Full House, Jacks full of Aces',
            'a Full House, Jacks full of Kings',
            'a Full House, Jacks full of Queens',
            'a Full House, Jacks full of Tens',
            'a Full House, Jacks full of Nines',
            'a Full House, Jacks full of Eights',
            'a Full House, Jacks full of Sevens',
            'a Full House, Jacks full of Sixes',
            'a Full House, Jacks full of Fives',
            'a Full House, Jacks full of Fours',
            'a Full House, Jacks full of Threes',
            'a Full House, Jacks full of Deuces',
            'a Full House, Tens full of Aces',
            'a Full House, Tens full of Kings',
            'a Full House, Tens full of Queens',
            'a Full House, Tens full of Jacks',
            'a Full House, Tens full of Nines',
            'a Full House, Tens full of Eights',
            'a Full House, Tens full of Sevens',
            'a Full House, Tens full of Sixes',
            'a Full House, Tens full of Fives',
            'a Full House, Tens full of Fours',
            'a Full House, Tens full of Threes',
            'a Full House, Tens full of Deuces',
            'a Full House, Nines full of Aces',
            'a Full House, Nines full of Kings',
            'a Full House, Nines full of Queens',
            'a Full House, Nines full of Jacks',
            'a Full House, Nines full of Tens',
            'a Full House, Nines full of Eights',
            'a Full House, Nines full of Sevens',
            'a Full House, Nines full of Sixes',
            'a Full House, Nines full of Fives',
            'a Full House, Nines full of Fours',
            'a Full House, Nines full of Threes',
            'a Full House, Nines full of Deuces',
            'a Full House, Eights full of Aces',
            'a Full House, Eights full of Kings',
            'a Full House, Eights full of Queens',
            'a Full House, Eights full of Jacks',
            'a Full House, Eights full of Tens',
            'a Full House, Eights full of Nines',
            'a Full House, Eights full of Sevens',
            'a Full House, Eights full of Sixes',
            'a Full House, Eights full of Fives',
            'a Full House, Eights full of Fours',
            'a Full House, Eights full of Threes',
            'a Full House, Eights full of Deuces',
            'a Full House, Sevens full of Aces',
            'a Full House, Sevens full of Kings',
            'a Full House, Sevens full of Queens',
            'a Full House, Sevens full of Jacks',
            'a Full House, Sevens full of Tens',
            'a Full House, Sevens full of Nines',
            'a Full House, Sevens full of Eights',
            'a Full House, Sevens full of Sixes',
            'a Full House, Sevens full of Fives',
            'a Full House, Sevens full of Fours',
            'a Full House, Sevens full of Threes',
            'a Full House, Sevens full of Deuces',
            'a Full House, Sixes full of Aces',
            'a Full House, Sixes full of Kings',
            'a Full House, Sixes full of Queens',
            'a Full House, Sixes full of Jacks',
            'a Full House, Sixes full of Tens',
            'a Full House, Sixes full of Nines',
            'a Full House, Sixes full of Eights',
            'a Full House, Sixes full of Sevens',
            'a Full House, Sixes full of Fives',
            'a Full House, Sixes full of Fours',
            'a Full House, Sixes full of Threes',
            'a Full House, Sixes full of Deuces',
            'a Full House, Fives full of Aces',
            'a Full House, Fives full of Kings',
            'a Full House, Fives full of Queens',
            'a Full House, Fives full of Jacks',
            'a Full House, Fives full of Tens',
            'a Full House, Fives full of Nines',
            'a Full House, Fives full of Eights',
            'a Full House, Fives full of Sevens',
            'a Full House, Fives full of Sixes',
            'a Full House, Fives full of Fours',
            'a Full House, Fives full of Threes',
            'a Full House, Fives full of Deuces',
            'a Full House, Fours full of Aces',
            'a Full House, Fours full of Kings',
            'a Full House, Fours full of Queens',
            'a Full House, Fours full of Jacks',
            'a Full House, Fours full of Tens',
            'a Full House, Fours full of Nines',
            'a Full House, Fours full of Eights',
            'a Full House, Fours full of Sevens',
            'a Full House, Fours full of Sixes',
            'a Full House, Fours full of Fives',
            'a Full House, Fours full of Threes',
            'a Full House, Fours full of Deuces',
            'a Full House, Threes full of Aces',
            'a Full House, Threes full of Kings',
            'a Full House, Threes full of Queens',
            'a Full House, Threes full of Jacks',
            'a Full House, Threes full of Tens',
            'a Full House, Threes full of Nines',
            'a Full House, Threes full of Eights',
            'a Full House, Threes full of Sevens',
            'a Full House, Threes full of Sixes',
            'a Full House, Threes full of Fives',
            'a Full House, Threes full of Fours',
            'a Full House, Threes full of Deuces',
            'a Full House, Deuces full of Aces',
            'a Full House, Deuces full of Kings',
            'a Full House, Deuces full of Queens',
            'a Full House, Deuces full of Jacks',
            'a Full House, Deuces full of Tens',
            'a Full House, Deuces full of Nines',
            'a Full House, Deuces full of Eights',
            'a Full House, Deuces full of Sevens',
            'a Full House, Deuces full of Sixes',
            'a Full House, Deuces full of Fives',
            'a Full House, Deuces full of Fours',
            'a Full House, Deuces full of Threes',
            'a Flush, Ace high +KQJ9',
            'a Flush, Ace high +KQJ8',
            'a Flush, Ace high +KQJ7',
            'a Flush, Ace high +KQJ6',
            'a Flush, Ace high +KQJ5',
            'a Flush, Ace high +KQJ4',
            'a Flush, Ace high +KQJ3',
            'a Flush, Ace high +KQJ2',
            'a Flush, Ace high +KQT9',
            'a Flush, Ace high +KQT8',
            'a Flush, Ace high +KQT7',
            'a Flush, Ace high +KQT6',
            'a Flush, Ace high +KQT5',
            'a Flush, Ace high +KQT4',
            'a Flush, Ace high +KQT3',
            'a Flush, Ace high +KQT2',
            'a Flush, Ace high +KQ98',
            'a Flush, Ace high +KQ97',
            'a Flush, Ace high +KQ96',
            'a Flush, Ace high +KQ95',
            'a Flush, Ace high +KQ94',
            'a Flush, Ace high +KQ93',
            'a Flush, Ace high +KQ92',
            'a Flush, Ace high +KQ87',
            'a Flush, Ace high +KQ86',
            'a Flush, Ace high +KQ85',
            'a Flush, Ace high +KQ84',
            'a Flush, Ace high +KQ83',
            'a Flush, Ace high +KQ82',
            'a Flush, Ace high +KQ76',
            'a Flush, Ace high +KQ75',
            'a Flush, Ace high +KQ74',
            'a Flush, Ace high +KQ73',
            'a Flush, Ace high +KQ72',
            'a Flush, Ace high +KQ65',
            'a Flush, Ace high +KQ64',
            'a Flush, Ace high +KQ63',
            'a Flush, Ace high +KQ62',
            'a Flush, Ace high +KQ54',
            'a Flush, Ace high +KQ53',
            'a Flush, Ace high +KQ52',
            'a Flush, Ace high +KQ43',
            'a Flush, Ace high +KQ42',
            'a Flush, Ace high +KQ32',
            'a Flush, Ace high +KJT9',
            'a Flush, Ace high +KJT8',
            'a Flush, Ace high +KJT7',
            'a Flush, Ace high +KJT6',
            'a Flush, Ace high +KJT5',
            'a Flush, Ace high +KJT4',
            'a Flush, Ace high +KJT3',
            'a Flush, Ace high +KJT2',
            'a Flush, Ace high +KJ98',
            'a Flush, Ace high +KJ97',
            'a Flush, Ace high +KJ96',
            'a Flush, Ace high +KJ95',
            'a Flush, Ace high +KJ94',
            'a Flush, Ace high +KJ93',
            'a Flush, Ace high +KJ92',
            'a Flush, Ace high +KJ87',
            'a Flush, Ace high +KJ86',
            'a Flush, Ace high +KJ85',
            'a Flush, Ace high +KJ84',
            'a Flush, Ace high +KJ83',
            'a Flush, Ace high +KJ82',
            'a Flush, Ace high +KJ76',
            'a Flush, Ace high +KJ75',
            'a Flush, Ace high +KJ74',
            'a Flush, Ace high +KJ73',
            'a Flush, Ace high +KJ72',
            'a Flush, Ace high +KJ65',
            'a Flush, Ace high +KJ64',
            'a Flush, Ace high +KJ63',
            'a Flush, Ace high +KJ62',
            'a Flush, Ace high +KJ54',
            'a Flush, Ace high +KJ53',
            'a Flush, Ace high +KJ52',
            'a Flush, Ace high +KJ43',
            'a Flush, Ace high +KJ42',
            'a Flush, Ace high +KJ32',
            'a Flush, Ace high +KT98',
            'a Flush, Ace high +KT97',
            'a Flush, Ace high +KT96',
            'a Flush, Ace high +KT95',
            'a Flush, Ace high +KT94',
            'a Flush, Ace high +KT93',
            'a Flush, Ace high +KT92',
            'a Flush, Ace high +KT87',
            'a Flush, Ace high +KT86',
            'a Flush, Ace high +KT85',
            'a Flush, Ace high +KT84',
            'a Flush, Ace high +KT83',
            'a Flush, Ace high +KT82',
            'a Flush, Ace high +KT76',
            'a Flush, Ace high +KT75',
            'a Flush, Ace high +KT74',
            'a Flush, Ace high +KT73',
            'a Flush, Ace high +KT72',
            'a Flush, Ace high +KT65',
            'a Flush, Ace high +KT64',
            'a Flush, Ace high +KT63',
            'a Flush, Ace high +KT62',
            'a Flush, Ace high +KT54',
            'a Flush, Ace high +KT53',
            'a Flush, Ace high +KT52',
            'a Flush, Ace high +KT43',
            'a Flush, Ace high +KT42',
            'a Flush, Ace high +KT32',
            'a Flush, Ace high +K987',
            'a Flush, Ace high +K986',
            'a Flush, Ace high +K985',
            'a Flush, Ace high +K984',
            'a Flush, Ace high +K983',
            'a Flush, Ace high +K982',
            'a Flush, Ace high +K976',
            'a Flush, Ace high +K975',
            'a Flush, Ace high +K974',
            'a Flush, Ace high +K973',
            'a Flush, Ace high +K972',
            'a Flush, Ace high +K965',
            'a Flush, Ace high +K964',
            'a Flush, Ace high +K963',
            'a Flush, Ace high +K962',
            'a Flush, Ace high +K954',
            'a Flush, Ace high +K953',
            'a Flush, Ace high +K952',
            'a Flush, Ace high +K943',
            'a Flush, Ace high +K942',
            'a Flush, Ace high +K932',
            'a Flush, Ace high +K876',
            'a Flush, Ace high +K875',
            'a Flush, Ace high +K874',
            'a Flush, Ace high +K873',
            'a Flush, Ace high +K872',
            'a Flush, Ace high +K865',
            'a Flush, Ace high +K864',
            'a Flush, Ace high +K863',
            'a Flush, Ace high +K862',
            'a Flush, Ace high +K854',
            'a Flush, Ace high +K853',
            'a Flush, Ace high +K852',
            'a Flush, Ace high +K843',
            'a Flush, Ace high +K842',
            'a Flush, Ace high +K832',
            'a Flush, Ace high +K765',
            'a Flush, Ace high +K764',
            'a Flush, Ace high +K763',
            'a Flush, Ace high +K762',
            'a Flush, Ace high +K754',
            'a Flush, Ace high +K753',
            'a Flush, Ace high +K752',
            'a Flush, Ace high +K743',
            'a Flush, Ace high +K742',
            'a Flush, Ace high +K732',
            'a Flush, Ace high +K654',
            'a Flush, Ace high +K653',
            'a Flush, Ace high +K652',
            'a Flush, Ace high +K643',
            'a Flush, Ace high +K642',
            'a Flush, Ace high +K632',
            'a Flush, Ace high +K543',
            'a Flush, Ace high +K542',
            'a Flush, Ace high +K532',
            'a Flush, Ace high +K432',
            'a Flush, Ace high +QJT9',
            'a Flush, Ace high +QJT8',
            'a Flush, Ace high +QJT7',
            'a Flush, Ace high +QJT6',
            'a Flush, Ace high +QJT5',
            'a Flush, Ace high +QJT4',
            'a Flush, Ace high +QJT3',
            'a Flush, Ace high +QJT2',
            'a Flush, Ace high +QJ98',
            'a Flush, Ace high +QJ97',
            'a Flush, Ace high +QJ96',
            'a Flush, Ace high +QJ95',
            'a Flush, Ace high +QJ94',
            'a Flush, Ace high +QJ93',
            'a Flush, Ace high +QJ92',
            'a Flush, Ace high +QJ87',
            'a Flush, Ace high +QJ86',
            'a Flush, Ace high +QJ85',
            'a Flush, Ace high +QJ84',
            'a Flush, Ace high +QJ83',
            'a Flush, Ace high +QJ82',
            'a Flush, Ace high +QJ76',
            'a Flush, Ace high +QJ75',
            'a Flush, Ace high +QJ74',
            'a Flush, Ace high +QJ73',
            'a Flush, Ace high +QJ72',
            'a Flush, Ace high +QJ65',
            'a Flush, Ace high +QJ64',
            'a Flush, Ace high +QJ63',
            'a Flush, Ace high +QJ62',
            'a Flush, Ace high +QJ54',
            'a Flush, Ace high +QJ53',
            'a Flush, Ace high +QJ52',
            'a Flush, Ace high +QJ43',
            'a Flush, Ace high +QJ42',
            'a Flush, Ace high +QJ32',
            'a Flush, Ace high +QT98',
            'a Flush, Ace high +QT97',
            'a Flush, Ace high +QT96',
            'a Flush, Ace high +QT95',
            'a Flush, Ace high +QT94',
            'a Flush, Ace high +QT93',
            'a Flush, Ace high +QT92',
            'a Flush, Ace high +QT87',
            'a Flush, Ace high +QT86',
            'a Flush, Ace high +QT85',
            'a Flush, Ace high +QT84',
            'a Flush, Ace high +QT83',
            'a Flush, Ace high +QT82',
            'a Flush, Ace high +QT76',
            'a Flush, Ace high +QT75',
            'a Flush, Ace high +QT74',
            'a Flush, Ace high +QT73',
            'a Flush, Ace high +QT72',
            'a Flush, Ace high +QT65',
            'a Flush, Ace high +QT64',
            'a Flush, Ace high +QT63',
            'a Flush, Ace high +QT62',
            'a Flush, Ace high +QT54',
            'a Flush, Ace high +QT53',
            'a Flush, Ace high +QT52',
            'a Flush, Ace high +QT43',
            'a Flush, Ace high +QT42',
            'a Flush, Ace high +QT32',
            'a Flush, Ace high +Q987',
            'a Flush, Ace high +Q986',
            'a Flush, Ace high +Q985',
            'a Flush, Ace high +Q984',
            'a Flush, Ace high +Q983',
            'a Flush, Ace high +Q982',
            'a Flush, Ace high +Q976',
            'a Flush, Ace high +Q975',
            'a Flush, Ace high +Q974',
            'a Flush, Ace high +Q973',
            'a Flush, Ace high +Q972',
            'a Flush, Ace high +Q965',
            'a Flush, Ace high +Q964',
            'a Flush, Ace high +Q963',
            'a Flush, Ace high +Q962',
            'a Flush, Ace high +Q954',
            'a Flush, Ace high +Q953',
            'a Flush, Ace high +Q952',
            'a Flush, Ace high +Q943',
            'a Flush, Ace high +Q942',
            'a Flush, Ace high +Q932',
            'a Flush, Ace high +Q876',
            'a Flush, Ace high +Q875',
            'a Flush, Ace high +Q874',
            'a Flush, Ace high +Q873',
            'a Flush, Ace high +Q872',
            'a Flush, Ace high +Q865',
            'a Flush, Ace high +Q864',
            'a Flush, Ace high +Q863',
            'a Flush, Ace high +Q862',
            'a Flush, Ace high +Q854',
            'a Flush, Ace high +Q853',
            'a Flush, Ace high +Q852',
            'a Flush, Ace high +Q843',
            'a Flush, Ace high +Q842',
            'a Flush, Ace high +Q832',
            'a Flush, Ace high +Q765',
            'a Flush, Ace high +Q764',
            'a Flush, Ace high +Q763',
            'a Flush, Ace high +Q762',
            'a Flush, Ace high +Q754',
            'a Flush, Ace high +Q753',
            'a Flush, Ace high +Q752',
            'a Flush, Ace high +Q743',
            'a Flush, Ace high +Q742',
            'a Flush, Ace high +Q732',
            'a Flush, Ace high +Q654',
            'a Flush, Ace high +Q653',
            'a Flush, Ace high +Q652',
            'a Flush, Ace high +Q643',
            'a Flush, Ace high +Q642',
            'a Flush, Ace high +Q632',
            'a Flush, Ace high +Q543',
            'a Flush, Ace high +Q542',
            'a Flush, Ace high +Q532',
            'a Flush, Ace high +Q432',
            'a Flush, Ace high +JT98',
            'a Flush, Ace high +JT97',
            'a Flush, Ace high +JT96',
            'a Flush, Ace high +JT95',
            'a Flush, Ace high +JT94',
            'a Flush, Ace high +JT93',
            'a Flush, Ace high +JT92',
            'a Flush, Ace high +JT87',
            'a Flush, Ace high +JT86',
            'a Flush, Ace high +JT85',
            'a Flush, Ace high +JT84',
            'a Flush, Ace high +JT83',
            'a Flush, Ace high +JT82',
            'a Flush, Ace high +JT76',
            'a Flush, Ace high +JT75',
            'a Flush, Ace high +JT74',
            'a Flush, Ace high +JT73',
            'a Flush, Ace high +JT72',
            'a Flush, Ace high +JT65',
            'a Flush, Ace high +JT64',
            'a Flush, Ace high +JT63',
            'a Flush, Ace high +JT62',
            'a Flush, Ace high +JT54',
            'a Flush, Ace high +JT53',
            'a Flush, Ace high +JT52',
            'a Flush, Ace high +JT43',
            'a Flush, Ace high +JT42',
            'a Flush, Ace high +JT32',
            'a Flush, Ace high +J987',
            'a Flush, Ace high +J986',
            'a Flush, Ace high +J985',
            'a Flush, Ace high +J984',
            'a Flush, Ace high +J983',
            'a Flush, Ace high +J982',
            'a Flush, Ace high +J976',
            'a Flush, Ace high +J975',
            'a Flush, Ace high +J974',
            'a Flush, Ace high +J973',
            'a Flush, Ace high +J972',
            'a Flush, Ace high +J965',
            'a Flush, Ace high +J964',
            'a Flush, Ace high +J963',
            'a Flush, Ace high +J962',
            'a Flush, Ace high +J954',
            'a Flush, Ace high +J953',
            'a Flush, Ace high +J952',
            'a Flush, Ace high +J943',
            'a Flush, Ace high +J942',
            'a Flush, Ace high +J932',
            'a Flush, Ace high +J876',
            'a Flush, Ace high +J875',
            'a Flush, Ace high +J874',
            'a Flush, Ace high +J873',
            'a Flush, Ace high +J872',
            'a Flush, Ace high +J865',
            'a Flush, Ace high +J864',
            'a Flush, Ace high +J863',
            'a Flush, Ace high +J862',
            'a Flush, Ace high +J854',
            'a Flush, Ace high +J853',
            'a Flush, Ace high +J852',
            'a Flush, Ace high +J843',
            'a Flush, Ace high +J842',
            'a Flush, Ace high +J832',
            'a Flush, Ace high +J765',
            'a Flush, Ace high +J764',
            'a Flush, Ace high +J763',
            'a Flush, Ace high +J762',
            'a Flush, Ace high +J754',
            'a Flush, Ace high +J753',
            'a Flush, Ace high +J752',
            'a Flush, Ace high +J743',
            'a Flush, Ace high +J742',
            'a Flush, Ace high +J732',
            'a Flush, Ace high +J654',
            'a Flush, Ace high +J653',
            'a Flush, Ace high +J652',
            'a Flush, Ace high +J643',
            'a Flush, Ace high +J642',
            'a Flush, Ace high +J632',
            'a Flush, Ace high +J543',
            'a Flush, Ace high +J542',
            'a Flush, Ace high +J532',
            'a Flush, Ace high +J432',
            'a Flush, Ace high +T987',
            'a Flush, Ace high +T986',
            'a Flush, Ace high +T985',
            'a Flush, Ace high +T984',
            'a Flush, Ace high +T983',
            'a Flush, Ace high +T982',
            'a Flush, Ace high +T976',
            'a Flush, Ace high +T975',
            'a Flush, Ace high +T974',
            'a Flush, Ace high +T973',
            'a Flush, Ace high +T972',
            'a Flush, Ace high +T965',
            'a Flush, Ace high +T964',
            'a Flush, Ace high +T963',
            'a Flush, Ace high +T962',
            'a Flush, Ace high +T954',
            'a Flush, Ace high +T953',
            'a Flush, Ace high +T952',
            'a Flush, Ace high +T943',
            'a Flush, Ace high +T942',
            'a Flush, Ace high +T932',
            'a Flush, Ace high +T876',
            'a Flush, Ace high +T875',
            'a Flush, Ace high +T874',
            'a Flush, Ace high +T873',
            'a Flush, Ace high +T872',
            'a Flush, Ace high +T865',
            'a Flush, Ace high +T864',
            'a Flush, Ace high +T863',
            'a Flush, Ace high +T862',
            'a Flush, Ace high +T854',
            'a Flush, Ace high +T853',
            'a Flush, Ace high +T852',
            'a Flush, Ace high +T843',
            'a Flush, Ace high +T842',
            'a Flush, Ace high +T832',
            'a Flush, Ace high +T765',
            'a Flush, Ace high +T764',
            'a Flush, Ace high +T763',
            'a Flush, Ace high +T762',
            'a Flush, Ace high +T754',
            'a Flush, Ace high +T753',
            'a Flush, Ace high +T752',
            'a Flush, Ace high +T743',
            'a Flush, Ace high +T742',
            'a Flush, Ace high +T732',
            'a Flush, Ace high +T654',
            'a Flush, Ace high +T653',
            'a Flush, Ace high +T652',
            'a Flush, Ace high +T643',
            'a Flush, Ace high +T642',
            'a Flush, Ace high +T632',
            'a Flush, Ace high +T543',
            'a Flush, Ace high +T542',
            'a Flush, Ace high +T532',
            'a Flush, Ace high +T432',
            'a Flush, Ace high +9876',
            'a Flush, Ace high +9875',
            'a Flush, Ace high +9874',
            'a Flush, Ace high +9873',
            'a Flush, Ace high +9872',
            'a Flush, Ace high +9865',
            'a Flush, Ace high +9864',
            'a Flush, Ace high +9863',
            'a Flush, Ace high +9862',
            'a Flush, Ace high +9854',
            'a Flush, Ace high +9853',
            'a Flush, Ace high +9852',
            'a Flush, Ace high +9843',
            'a Flush, Ace high +9842',
            'a Flush, Ace high +9832',
            'a Flush, Ace high +9765',
            'a Flush, Ace high +9764',
            'a Flush, Ace high +9763',
            'a Flush, Ace high +9762',
            'a Flush, Ace high +9754',
            'a Flush, Ace high +9753',
            'a Flush, Ace high +9752',
            'a Flush, Ace high +9743',
            'a Flush, Ace high +9742',
            'a Flush, Ace high +9732',
            'a Flush, Ace high +9654',
            'a Flush, Ace high +9653',
            'a Flush, Ace high +9652',
            'a Flush, Ace high +9643',
            'a Flush, Ace high +9642',
            'a Flush, Ace high +9632',
            'a Flush, Ace high +9543',
            'a Flush, Ace high +9542',
            'a Flush, Ace high +9532',
            'a Flush, Ace high +9432',
            'a Flush, Ace high +8765',
            'a Flush, Ace high +8764',
            'a Flush, Ace high +8763',
            'a Flush, Ace high +8762',
            'a Flush, Ace high +8754',
            'a Flush, Ace high +8753',
            'a Flush, Ace high +8752',
            'a Flush, Ace high +8743',
            'a Flush, Ace high +8742',
            'a Flush, Ace high +8732',
            'a Flush, Ace high +8654',
            'a Flush, Ace high +8653',
            'a Flush, Ace high +8652',
            'a Flush, Ace high +8643',
            'a Flush, Ace high +8642',
            'a Flush, Ace high +8632',
            'a Flush, Ace high +8543',
            'a Flush, Ace high +8542',
            'a Flush, Ace high +8532',
            'a Flush, Ace high +8432',
            'a Flush, Ace high +7654',
            'a Flush, Ace high +7653',
            'a Flush, Ace high +7652',
            'a Flush, Ace high +7643',
            'a Flush, Ace high +7642',
            'a Flush, Ace high +7632',
            'a Flush, Ace high +7543',
            'a Flush, Ace high +7542',
            'a Flush, Ace high +7532',
            'a Flush, Ace high +7432',
            'a Flush, Ace high +6543',
            'a Flush, Ace high +6542',
            'a Flush, Ace high +6532',
            'a Flush, Ace high +6432',
            'a Flush, King high +QJT8',
            'a Flush, King high +QJT7',
            'a Flush, King high +QJT6',
            'a Flush, King high +QJT5',
            'a Flush, King high +QJT4',
            'a Flush, King high +QJT3',
            'a Flush, King high +QJT2',
            'a Flush, King high +QJ98',
            'a Flush, King high +QJ97',
            'a Flush, King high +QJ96',
            'a Flush, King high +QJ95',
            'a Flush, King high +QJ94',
            'a Flush, King high +QJ93',
            'a Flush, King high +QJ92',
            'a Flush, King high +QJ87',
            'a Flush, King high +QJ86',
            'a Flush, King high +QJ85',
            'a Flush, King high +QJ84',
            'a Flush, King high +QJ83',
            'a Flush, King high +QJ82',
            'a Flush, King high +QJ76',
            'a Flush, King high +QJ75',
            'a Flush, King high +QJ74',
            'a Flush, King high +QJ73',
            'a Flush, King high +QJ72',
            'a Flush, King high +QJ65',
            'a Flush, King high +QJ64',
            'a Flush, King high +QJ63',
            'a Flush, King high +QJ62',
            'a Flush, King high +QJ54',
            'a Flush, King high +QJ53',
            'a Flush, King high +QJ52',
            'a Flush, King high +QJ43',
            'a Flush, King high +QJ42',
            'a Flush, King high +QJ32',
            'a Flush, King high +QT98',
            'a Flush, King high +QT97',
            'a Flush, King high +QT96',
            'a Flush, King high +QT95',
            'a Flush, King high +QT94',
            'a Flush, King high +QT93',
            'a Flush, King high +QT92',
            'a Flush, King high +QT87',
            'a Flush, King high +QT86',
            'a Flush, King high +QT85',
            'a Flush, King high +QT84',
            'a Flush, King high +QT83',
            'a Flush, King high +QT82',
            'a Flush, King high +QT76',
            'a Flush, King high +QT75',
            'a Flush, King high +QT74',
            'a Flush, King high +QT73',
            'a Flush, King high +QT72',
            'a Flush, King high +QT65',
            'a Flush, King high +QT64',
            'a Flush, King high +QT63',
            'a Flush, King high +QT62',
            'a Flush, King high +QT54',
            'a Flush, King high +QT53',
            'a Flush, King high +QT52',
            'a Flush, King high +QT43',
            'a Flush, King high +QT42',
            'a Flush, King high +QT32',
            'a Flush, King high +Q987',
            'a Flush, King high +Q986',
            'a Flush, King high +Q985',
            'a Flush, King high +Q984',
            'a Flush, King high +Q983',
            'a Flush, King high +Q982',
            'a Flush, King high +Q976',
            'a Flush, King high +Q975',
            'a Flush, King high +Q974',
            'a Flush, King high +Q973',
            'a Flush, King high +Q972',
            'a Flush, King high +Q965',
            'a Flush, King high +Q964',
            'a Flush, King high +Q963',
            'a Flush, King high +Q962',
            'a Flush, King high +Q954',
            'a Flush, King high +Q953',
            'a Flush, King high +Q952',
            'a Flush, King high +Q943',
            'a Flush, King high +Q942',
            'a Flush, King high +Q932',
            'a Flush, King high +Q876',
            'a Flush, King high +Q875',
            'a Flush, King high +Q874',
            'a Flush, King high +Q873',
            'a Flush, King high +Q872',
            'a Flush, King high +Q865',
            'a Flush, King high +Q864',
            'a Flush, King high +Q863',
            'a Flush, King high +Q862',
            'a Flush, King high +Q854',
            'a Flush, King high +Q853',
            'a Flush, King high +Q852',
            'a Flush, King high +Q843',
            'a Flush, King high +Q842',
            'a Flush, King high +Q832',
            'a Flush, King high +Q765',
            'a Flush, King high +Q764',
            'a Flush, King high +Q763',
            'a Flush, King high +Q762',
            'a Flush, King high +Q754',
            'a Flush, King high +Q753',
            'a Flush, King high +Q752',
            'a Flush, King high +Q743',
            'a Flush, King high +Q742',
            'a Flush, King high +Q732',
            'a Flush, King high +Q654',
            'a Flush, King high +Q653',
            'a Flush, King high +Q652',
            'a Flush, King high +Q643',
            'a Flush, King high +Q642',
            'a Flush, King high +Q632',
            'a Flush, King high +Q543',
            'a Flush, King high +Q542',
            'a Flush, King high +Q532',
            'a Flush, King high +Q432',
            'a Flush, King high +JT98',
            'a Flush, King high +JT97',
            'a Flush, King high +JT96',
            'a Flush, King high +JT95',
            'a Flush, King high +JT94',
            'a Flush, King high +JT93',
            'a Flush, King high +JT92',
            'a Flush, King high +JT87',
            'a Flush, King high +JT86',
            'a Flush, King high +JT85',
            'a Flush, King high +JT84',
            'a Flush, King high +JT83',
            'a Flush, King high +JT82',
            'a Flush, King high +JT76',
            'a Flush, King high +JT75',
            'a Flush, King high +JT74',
            'a Flush, King high +JT73',
            'a Flush, King high +JT72',
            'a Flush, King high +JT65',
            'a Flush, King high +JT64',
            'a Flush, King high +JT63',
            'a Flush, King high +JT62',
            'a Flush, King high +JT54',
            'a Flush, King high +JT53',
            'a Flush, King high +JT52',
            'a Flush, King high +JT43',
            'a Flush, King high +JT42',
            'a Flush, King high +JT32',
            'a Flush, King high +J987',
            'a Flush, King high +J986',
            'a Flush, King high +J985',
            'a Flush, King high +J984',
            'a Flush, King high +J983',
            'a Flush, King high +J982',
            'a Flush, King high +J976',
            'a Flush, King high +J975',
            'a Flush, King high +J974',
            'a Flush, King high +J973',
            'a Flush, King high +J972',
            'a Flush, King high +J965',
            'a Flush, King high +J964',
            'a Flush, King high +J963',
            'a Flush, King high +J962',
            'a Flush, King high +J954',
            'a Flush, King high +J953',
            'a Flush, King high +J952',
            'a Flush, King high +J943',
            'a Flush, King high +J942',
            'a Flush, King high +J932',
            'a Flush, King high +J876',
            'a Flush, King high +J875',
            'a Flush, King high +J874',
            'a Flush, King high +J873',
            'a Flush, King high +J872',
            'a Flush, King high +J865',
            'a Flush, King high +J864',
            'a Flush, King high +J863',
            'a Flush, King high +J862',
            'a Flush, King high +J854',
            'a Flush, King high +J853',
            'a Flush, King high +J852',
            'a Flush, King high +J843',
            'a Flush, King high +J842',
            'a Flush, King high +J832',
            'a Flush, King high +J765',
            'a Flush, King high +J764',
            'a Flush, King high +J763',
            'a Flush, King high +J762',
            'a Flush, King high +J754',
            'a Flush, King high +J753',
            'a Flush, King high +J752',
            'a Flush, King high +J743',
            'a Flush, King high +J742',
            'a Flush, King high +J732',
            'a Flush, King high +J654',
            'a Flush, King high +J653',
            'a Flush, King high +J652',
            'a Flush, King high +J643',
            'a Flush, King high +J642',
            'a Flush, King high +J632',
            'a Flush, King high +J543',
            'a Flush, King high +J542',
            'a Flush, King high +J532',
            'a Flush, King high +J432',
            'a Flush, King high +T987',
            'a Flush, King high +T986',
            'a Flush, King high +T985',
            'a Flush, King high +T984',
            'a Flush, King high +T983',
            'a Flush, King high +T982',
            'a Flush, King high +T976',
            'a Flush, King high +T975',
            'a Flush, King high +T974',
            'a Flush, King high +T973',
            'a Flush, King high +T972',
            'a Flush, King high +T965',
            'a Flush, King high +T964',
            'a Flush, King high +T963',
            'a Flush, King high +T962',
            'a Flush, King high +T954',
            'a Flush, King high +T953',
            'a Flush, King high +T952',
            'a Flush, King high +T943',
            'a Flush, King high +T942',
            'a Flush, King high +T932',
            'a Flush, King high +T876',
            'a Flush, King high +T875',
            'a Flush, King high +T874',
            'a Flush, King high +T873',
            'a Flush, King high +T872',
            'a Flush, King high +T865',
            'a Flush, King high +T864',
            'a Flush, King high +T863',
            'a Flush, King high +T862',
            'a Flush, King high +T854',
            'a Flush, King high +T853',
            'a Flush, King high +T852',
            'a Flush, King high +T843',
            'a Flush, King high +T842',
            'a Flush, King high +T832',
            'a Flush, King high +T765',
            'a Flush, King high +T764',
            'a Flush, King high +T763',
            'a Flush, King high +T762',
            'a Flush, King high +T754',
            'a Flush, King high +T753',
            'a Flush, King high +T752',
            'a Flush, King high +T743',
            'a Flush, King high +T742',
            'a Flush, King high +T732',
            'a Flush, King high +T654',
            'a Flush, King high +T653',
            'a Flush, King high +T652',
            'a Flush, King high +T643',
            'a Flush, King high +T642',
            'a Flush, King high +T632',
            'a Flush, King high +T543',
            'a Flush, King high +T542',
            'a Flush, King high +T532',
            'a Flush, King high +T432',
            'a Flush, King high +9876',
            'a Flush, King high +9875',
            'a Flush, King high +9874',
            'a Flush, King high +9873',
            'a Flush, King high +9872',
            'a Flush, King high +9865',
            'a Flush, King high +9864',
            'a Flush, King high +9863',
            'a Flush, King high +9862',
            'a Flush, King high +9854',
            'a Flush, King high +9853',
            'a Flush, King high +9852',
            'a Flush, King high +9843',
            'a Flush, King high +9842',
            'a Flush, King high +9832',
            'a Flush, King high +9765',
            'a Flush, King high +9764',
            'a Flush, King high +9763',
            'a Flush, King high +9762',
            'a Flush, King high +9754',
            'a Flush, King high +9753',
            'a Flush, King high +9752',
            'a Flush, King high +9743',
            'a Flush, King high +9742',
            'a Flush, King high +9732',
            'a Flush, King high +9654',
            'a Flush, King high +9653',
            'a Flush, King high +9652',
            'a Flush, King high +9643',
            'a Flush, King high +9642',
            'a Flush, King high +9632',
            'a Flush, King high +9543',
            'a Flush, King high +9542',
            'a Flush, King high +9532',
            'a Flush, King high +9432',
            'a Flush, King high +8765',
            'a Flush, King high +8764',
            'a Flush, King high +8763',
            'a Flush, King high +8762',
            'a Flush, King high +8754',
            'a Flush, King high +8753',
            'a Flush, King high +8752',
            'a Flush, King high +8743',
            'a Flush, King high +8742',
            'a Flush, King high +8732',
            'a Flush, King high +8654',
            'a Flush, King high +8653',
            'a Flush, King high +8652',
            'a Flush, King high +8643',
            'a Flush, King high +8642',
            'a Flush, King high +8632',
            'a Flush, King high +8543',
            'a Flush, King high +8542',
            'a Flush, King high +8532',
            'a Flush, King high +8432',
            'a Flush, King high +7654',
            'a Flush, King high +7653',
            'a Flush, King high +7652',
            'a Flush, King high +7643',
            'a Flush, King high +7642',
            'a Flush, King high +7632',
            'a Flush, King high +7543',
            'a Flush, King high +7542',
            'a Flush, King high +7532',
            'a Flush, King high +7432',
            'a Flush, King high +6543',
            'a Flush, King high +6542',
            'a Flush, King high +6532',
            'a Flush, King high +6432',
            'a Flush, King high +5432',
            'a Flush, Queen high +JT97',
            'a Flush, Queen high +JT96',
            'a Flush, Queen high +JT95',
            'a Flush, Queen high +JT94',
            'a Flush, Queen high +JT93',
            'a Flush, Queen high +JT92',
            'a Flush, Queen high +JT87',
            'a Flush, Queen high +JT86',
            'a Flush, Queen high +JT85',
            'a Flush, Queen high +JT84',
            'a Flush, Queen high +JT83',
            'a Flush, Queen high +JT82',
            'a Flush, Queen high +JT76',
            'a Flush, Queen high +JT75',
            'a Flush, Queen high +JT74',
            'a Flush, Queen high +JT73',
            'a Flush, Queen high +JT72',
            'a Flush, Queen high +JT65',
            'a Flush, Queen high +JT64',
            'a Flush, Queen high +JT63',
            'a Flush, Queen high +JT62',
            'a Flush, Queen high +JT54',
            'a Flush, Queen high +JT53',
            'a Flush, Queen high +JT52',
            'a Flush, Queen high +JT43',
            'a Flush, Queen high +JT42',
            'a Flush, Queen high +JT32',
            'a Flush, Queen high +J987',
            'a Flush, Queen high +J986',
            'a Flush, Queen high +J985',
            'a Flush, Queen high +J984',
            'a Flush, Queen high +J983',
            'a Flush, Queen high +J982',
            'a Flush, Queen high +J976',
            'a Flush, Queen high +J975',
            'a Flush, Queen high +J974',
            'a Flush, Queen high +J973',
            'a Flush, Queen high +J972',
            'a Flush, Queen high +J965',
            'a Flush, Queen high +J964',
            'a Flush, Queen high +J963',
            'a Flush, Queen high +J962',
            'a Flush, Queen high +J954',
            'a Flush, Queen high +J953',
            'a Flush, Queen high +J952',
            'a Flush, Queen high +J943',
            'a Flush, Queen high +J942',
            'a Flush, Queen high +J932',
            'a Flush, Queen high +J876',
            'a Flush, Queen high +J875',
            'a Flush, Queen high +J874',
            'a Flush, Queen high +J873',
            'a Flush, Queen high +J872',
            'a Flush, Queen high +J865',
            'a Flush, Queen high +J864',
            'a Flush, Queen high +J863',
            'a Flush, Queen high +J862',
            'a Flush, Queen high +J854',
            'a Flush, Queen high +J853',
            'a Flush, Queen high +J852',
            'a Flush, Queen high +J843',
            'a Flush, Queen high +J842',
            'a Flush, Queen high +J832',
            'a Flush, Queen high +J765',
            'a Flush, Queen high +J764',
            'a Flush, Queen high +J763',
            'a Flush, Queen high +J762',
            'a Flush, Queen high +J754',
            'a Flush, Queen high +J753',
            'a Flush, Queen high +J752',
            'a Flush, Queen high +J743',
            'a Flush, Queen high +J742',
            'a Flush, Queen high +J732',
            'a Flush, Queen high +J654',
            'a Flush, Queen high +J653',
            'a Flush, Queen high +J652',
            'a Flush, Queen high +J643',
            'a Flush, Queen high +J642',
            'a Flush, Queen high +J632',
            'a Flush, Queen high +J543',
            'a Flush, Queen high +J542',
            'a Flush, Queen high +J532',
            'a Flush, Queen high +J432',
            'a Flush, Queen high +T987',
            'a Flush, Queen high +T986',
            'a Flush, Queen high +T985',
            'a Flush, Queen high +T984',
            'a Flush, Queen high +T983',
            'a Flush, Queen high +T982',
            'a Flush, Queen high +T976',
            'a Flush, Queen high +T975',
            'a Flush, Queen high +T974',
            'a Flush, Queen high +T973',
            'a Flush, Queen high +T972',
            'a Flush, Queen high +T965',
            'a Flush, Queen high +T964',
            'a Flush, Queen high +T963',
            'a Flush, Queen high +T962',
            'a Flush, Queen high +T954',
            'a Flush, Queen high +T953',
            'a Flush, Queen high +T952',
            'a Flush, Queen high +T943',
            'a Flush, Queen high +T942',
            'a Flush, Queen high +T932',
            'a Flush, Queen high +T876',
            'a Flush, Queen high +T875',
            'a Flush, Queen high +T874',
            'a Flush, Queen high +T873',
            'a Flush, Queen high +T872',
            'a Flush, Queen high +T865',
            'a Flush, Queen high +T864',
            'a Flush, Queen high +T863',
            'a Flush, Queen high +T862',
            'a Flush, Queen high +T854',
            'a Flush, Queen high +T853',
            'a Flush, Queen high +T852',
            'a Flush, Queen high +T843',
            'a Flush, Queen high +T842',
            'a Flush, Queen high +T832',
            'a Flush, Queen high +T765',
            'a Flush, Queen high +T764',
            'a Flush, Queen high +T763',
            'a Flush, Queen high +T762',
            'a Flush, Queen high +T754',
            'a Flush, Queen high +T753',
            'a Flush, Queen high +T752',
            'a Flush, Queen high +T743',
            'a Flush, Queen high +T742',
            'a Flush, Queen high +T732',
            'a Flush, Queen high +T654',
            'a Flush, Queen high +T653',
            'a Flush, Queen high +T652',
            'a Flush, Queen high +T643',
            'a Flush, Queen high +T642',
            'a Flush, Queen high +T632',
            'a Flush, Queen high +T543',
            'a Flush, Queen high +T542',
            'a Flush, Queen high +T532',
            'a Flush, Queen high +T432',
            'a Flush, Queen high +9876',
            'a Flush, Queen high +9875',
            'a Flush, Queen high +9874',
            'a Flush, Queen high +9873',
            'a Flush, Queen high +9872',
            'a Flush, Queen high +9865',
            'a Flush, Queen high +9864',
            'a Flush, Queen high +9863',
            'a Flush, Queen high +9862',
            'a Flush, Queen high +9854',
            'a Flush, Queen high +9853',
            'a Flush, Queen high +9852',
            'a Flush, Queen high +9843',
            'a Flush, Queen high +9842',
            'a Flush, Queen high +9832',
            'a Flush, Queen high +9765',
            'a Flush, Queen high +9764',
            'a Flush, Queen high +9763',
            'a Flush, Queen high +9762',
            'a Flush, Queen high +9754',
            'a Flush, Queen high +9753',
            'a Flush, Queen high +9752',
            'a Flush, Queen high +9743',
            'a Flush, Queen high +9742',
            'a Flush, Queen high +9732',
            'a Flush, Queen high +9654',
            'a Flush, Queen high +9653',
            'a Flush, Queen high +9652',
            'a Flush, Queen high +9643',
            'a Flush, Queen high +9642',
            'a Flush, Queen high +9632',
            'a Flush, Queen high +9543',
            'a Flush, Queen high +9542',
            'a Flush, Queen high +9532',
            'a Flush, Queen high +9432',
            'a Flush, Queen high +8765',
            'a Flush, Queen high +8764',
            'a Flush, Queen high +8763',
            'a Flush, Queen high +8762',
            'a Flush, Queen high +8754',
            'a Flush, Queen high +8753',
            'a Flush, Queen high +8752',
            'a Flush, Queen high +8743',
            'a Flush, Queen high +8742',
            'a Flush, Queen high +8732',
            'a Flush, Queen high +8654',
            'a Flush, Queen high +8653',
            'a Flush, Queen high +8652',
            'a Flush, Queen high +8643',
            'a Flush, Queen high +8642',
            'a Flush, Queen high +8632',
            'a Flush, Queen high +8543',
            'a Flush, Queen high +8542',
            'a Flush, Queen high +8532',
            'a Flush, Queen high +8432',
            'a Flush, Queen high +7654',
            'a Flush, Queen high +7653',
            'a Flush, Queen high +7652',
            'a Flush, Queen high +7643',
            'a Flush, Queen high +7642',
            'a Flush, Queen high +7632',
            'a Flush, Queen high +7543',
            'a Flush, Queen high +7542',
            'a Flush, Queen high +7532',
            'a Flush, Queen high +7432',
            'a Flush, Queen high +6543',
            'a Flush, Queen high +6542',
            'a Flush, Queen high +6532',
            'a Flush, Queen high +6432',
            'a Flush, Queen high +5432',
            'a Flush, Jack high +T986',
            'a Flush, Jack high +T985',
            'a Flush, Jack high +T984',
            'a Flush, Jack high +T983',
            'a Flush, Jack high +T982',
            'a Flush, Jack high +T976',
            'a Flush, Jack high +T975',
            'a Flush, Jack high +T974',
            'a Flush, Jack high +T973',
            'a Flush, Jack high +T972',
            'a Flush, Jack high +T965',
            'a Flush, Jack high +T964',
            'a Flush, Jack high +T963',
            'a Flush, Jack high +T962',
            'a Flush, Jack high +T954',
            'a Flush, Jack high +T953',
            'a Flush, Jack high +T952',
            'a Flush, Jack high +T943',
            'a Flush, Jack high +T942',
            'a Flush, Jack high +T932',
            'a Flush, Jack high +T876',
            'a Flush, Jack high +T875',
            'a Flush, Jack high +T874',
            'a Flush, Jack high +T873',
            'a Flush, Jack high +T872',
            'a Flush, Jack high +T865',
            'a Flush, Jack high +T864',
            'a Flush, Jack high +T863',
            'a Flush, Jack high +T862',
            'a Flush, Jack high +T854',
            'a Flush, Jack high +T853',
            'a Flush, Jack high +T852',
            'a Flush, Jack high +T843',
            'a Flush, Jack high +T842',
            'a Flush, Jack high +T832',
            'a Flush, Jack high +T765',
            'a Flush, Jack high +T764',
            'a Flush, Jack high +T763',
            'a Flush, Jack high +T762',
            'a Flush, Jack high +T754',
            'a Flush, Jack high +T753',
            'a Flush, Jack high +T752',
            'a Flush, Jack high +T743',
            'a Flush, Jack high +T742',
            'a Flush, Jack high +T732',
            'a Flush, Jack high +T654',
            'a Flush, Jack high +T653',
            'a Flush, Jack high +T652',
            'a Flush, Jack high +T643',
            'a Flush, Jack high +T642',
            'a Flush, Jack high +T632',
            'a Flush, Jack high +T543',
            'a Flush, Jack high +T542',
            'a Flush, Jack high +T532',
            'a Flush, Jack high +T432',
            'a Flush, Jack high +9876',
            'a Flush, Jack high +9875',
            'a Flush, Jack high +9874',
            'a Flush, Jack high +9873',
            'a Flush, Jack high +9872',
            'a Flush, Jack high +9865',
            'a Flush, Jack high +9864',
            'a Flush, Jack high +9863',
            'a Flush, Jack high +9862',
            'a Flush, Jack high +9854',
            'a Flush, Jack high +9853',
            'a Flush, Jack high +9852',
            'a Flush, Jack high +9843',
            'a Flush, Jack high +9842',
            'a Flush, Jack high +9832',
            'a Flush, Jack high +9765',
            'a Flush, Jack high +9764',
            'a Flush, Jack high +9763',
            'a Flush, Jack high +9762',
            'a Flush, Jack high +9754',
            'a Flush, Jack high +9753',
            'a Flush, Jack high +9752',
            'a Flush, Jack high +9743',
            'a Flush, Jack high +9742',
            'a Flush, Jack high +9732',
            'a Flush, Jack high +9654',
            'a Flush, Jack high +9653',
            'a Flush, Jack high +9652',
            'a Flush, Jack high +9643',
            'a Flush, Jack high +9642',
            'a Flush, Jack high +9632',
            'a Flush, Jack high +9543',
            'a Flush, Jack high +9542',
            'a Flush, Jack high +9532',
            'a Flush, Jack high +9432',
            'a Flush, Jack high +8765',
            'a Flush, Jack high +8764',
            'a Flush, Jack high +8763',
            'a Flush, Jack high +8762',
            'a Flush, Jack high +8754',
            'a Flush, Jack high +8753',
            'a Flush, Jack high +8752',
            'a Flush, Jack high +8743',
            'a Flush, Jack high +8742',
            'a Flush, Jack high +8732',
            'a Flush, Jack high +8654',
            'a Flush, Jack high +8653',
            'a Flush, Jack high +8652',
            'a Flush, Jack high +8643',
            'a Flush, Jack high +8642',
            'a Flush, Jack high +8632',
            'a Flush, Jack high +8543',
            'a Flush, Jack high +8542',
            'a Flush, Jack high +8532',
            'a Flush, Jack high +8432',
            'a Flush, Jack high +7654',
            'a Flush, Jack high +7653',
            'a Flush, Jack high +7652',
            'a Flush, Jack high +7643',
            'a Flush, Jack high +7642',
            'a Flush, Jack high +7632',
            'a Flush, Jack high +7543',
            'a Flush, Jack high +7542',
            'a Flush, Jack high +7532',
            'a Flush, Jack high +7432',
            'a Flush, Jack high +6543',
            'a Flush, Jack high +6542',
            'a Flush, Jack high +6532',
            'a Flush, Jack high +6432',
            'a Flush, Jack high +5432',
            'a Flush, Ten high +9875',
            'a Flush, Ten high +9874',
            'a Flush, Ten high +9873',
            'a Flush, Ten high +9872',
            'a Flush, Ten high +9865',
            'a Flush, Ten high +9864',
            'a Flush, Ten high +9863',
            'a Flush, Ten high +9862',
            'a Flush, Ten high +9854',
            'a Flush, Ten high +9853',
            'a Flush, Ten high +9852',
            'a Flush, Ten high +9843',
            'a Flush, Ten high +9842',
            'a Flush, Ten high +9832',
            'a Flush, Ten high +9765',
            'a Flush, Ten high +9764',
            'a Flush, Ten high +9763',
            'a Flush, Ten high +9762',
            'a Flush, Ten high +9754',
            'a Flush, Ten high +9753',
            'a Flush, Ten high +9752',
            'a Flush, Ten high +9743',
            'a Flush, Ten high +9742',
            'a Flush, Ten high +9732',
            'a Flush, Ten high +9654',
            'a Flush, Ten high +9653',
            'a Flush, Ten high +9652',
            'a Flush, Ten high +9643',
            'a Flush, Ten high +9642',
            'a Flush, Ten high +9632',
            'a Flush, Ten high +9543',
            'a Flush, Ten high +9542',
            'a Flush, Ten high +9532',
            'a Flush, Ten high +9432',
            'a Flush, Ten high +8765',
            'a Flush, Ten high +8764',
            'a Flush, Ten high +8763',
            'a Flush, Ten high +8762',
            'a Flush, Ten high +8754',
            'a Flush, Ten high +8753',
            'a Flush, Ten high +8752',
            'a Flush, Ten high +8743',
            'a Flush, Ten high +8742',
            'a Flush, Ten high +8732',
            'a Flush, Ten high +8654',
            'a Flush, Ten high +8653',
            'a Flush, Ten high +8652',
            'a Flush, Ten high +8643',
            'a Flush, Ten high +8642',
            'a Flush, Ten high +8632',
            'a Flush, Ten high +8543',
            'a Flush, Ten high +8542',
            'a Flush, Ten high +8532',
            'a Flush, Ten high +8432',
            'a Flush, Ten high +7654',
            'a Flush, Ten high +7653',
            'a Flush, Ten high +7652',
            'a Flush, Ten high +7643',
            'a Flush, Ten high +7642',
            'a Flush, Ten high +7632',
            'a Flush, Ten high +7543',
            'a Flush, Ten high +7542',
            'a Flush, Ten high +7532',
            'a Flush, Ten high +7432',
            'a Flush, Ten high +6543',
            'a Flush, Ten high +6542',
            'a Flush, Ten high +6532',
            'a Flush, Ten high +6432',
            'a Flush, Ten high +5432',
            'a Flush, Nine high +8764',
            'a Flush, Nine high +8763',
            'a Flush, Nine high +8762',
            'a Flush, Nine high +8754',
            'a Flush, Nine high +8753',
            'a Flush, Nine high +8752',
            'a Flush, Nine high +8743',
            'a Flush, Nine high +8742',
            'a Flush, Nine high +8732',
            'a Flush, Nine high +8654',
            'a Flush, Nine high +8653',
            'a Flush, Nine high +8652',
            'a Flush, Nine high +8643',
            'a Flush, Nine high +8642',
            'a Flush, Nine high +8632',
            'a Flush, Nine high +8543',
            'a Flush, Nine high +8542',
            'a Flush, Nine high +8532',
            'a Flush, Nine high +8432',
            'a Flush, Nine high +7654',
            'a Flush, Nine high +7653',
            'a Flush, Nine high +7652',
            'a Flush, Nine high +7643',
            'a Flush, Nine high +7642',
            'a Flush, Nine high +7632',
            'a Flush, Nine high +7543',
            'a Flush, Nine high +7542',
            'a Flush, Nine high +7532',
            'a Flush, Nine high +7432',
            'a Flush, Nine high +6543',
            'a Flush, Nine high +6542',
            'a Flush, Nine high +6532',
            'a Flush, Nine high +6432',
            'a Flush, Nine high +5432',
            'a Flush, EighThigh +7653',
            'a Flush, EighThigh +7652',
            'a Flush, EighThigh +7643',
            'a Flush, EighThigh +7642',
            'a Flush, EighThigh +7632',
            'a Flush, EighThigh +7543',
            'a Flush, EighThigh +7542',
            'a Flush, EighThigh +7532',
            'a Flush, EighThigh +7432',
            'a Flush, EighThigh +6543',
            'a Flush, EighThigh +6542',
            'a Flush, EighThigh +6532',
            'a Flush, EighThigh +6432',
            'a Flush, EighThigh +5432',
            'a Flush, Seven high +6542',
            'a Flush, Seven high +6532',
            'a Flush, Seven high +6432',
            'a Flush, Seven high +5432');
        $parameters = array(
            "conditions" => "hand_value is Null AND hand is not NULL",
        );
        $hand_histories = HandHistories::find($parameters);

        foreach ($hand_histories as $hand_history) {
            $key = array_search($hand_history->hand, $hand_values);
            if ($key !== false) {
                $hand_history->update(
                    array("hand_value" => 1600 - $key)
                );
            } else {
                $hand_history->update(
                    array("hand_value" => 0)
                );
            }
        }
        $this->flash->success("The Hand Values updated successfully.");
    }

    public function connectionAction()
    {
        $params = array("Command" => "ConnectionsList",
            "Fields" => "SessionID, Status, Player, PC, IP, Connect, Login, LastAction, PacketsIn, PacketsOut",
        );
        $api = $this->getDI()->getApi()->poker($params);
        $this->view->AccountsGet = $api;
        // Pass all
    }

    public function logErrorAction()
    {
        if ($this->request->isPost()) {

            // Get the parameter

            $date = $this->request->getPost('date');

            if (!empty($date)) {
                $params = array("Command" => "LogsError",
                    "Date" => $date,
                );
                $api = $this->getDI()->getApi()->poker($params);

                if ($api->Result == "Ok") {
                    $this->view->events = $api->Data;
                } else {
                    $this->view->error = $api->Error;
                }
            }
        }
        // Pass all
        $params = array("Command" => "LogsError",
        );
        $api = $this->getDI()->getApi()->poker($params);
        $out = array();
        foreach ($api->Date as $key => $value)
            $out[$value] = $value;

        $this->view->LogsError = $out;
    }

    public function logEventAction()
    {
        if ($this->request->isPost()) {

            // Get the parameter

            $date = $this->request->getPost('date');

            if (!empty($date)) {
                $params = array("Command" => "LogsEvent",
                    "Date" => $date,
                );
                $api = $this->getDI()->getApi()->poker($params);

                if ($api->Result == "Ok") {
                    $this->view->events = $api->Data;
                } else {
                    $this->view->error = $api->Error;
                }
            }
        }
        // Pass all
        $params = array("Command" => "LogsEvent",
        );
        $api = $this->getDI()->getApi()->poker($params);
        $out = array();
        foreach ($api->Date as $key => $value)
            $out[$value] = $value;

        $this->view->LogsEvent = $out;
    }

    public function logHandHistoryAction()
    {
        if ($this->request->isPost()) {

            // Get the parameter

            $date = $this->request->getPost('date');
            $name = $this->request->getPost('name');
            if (!empty($date) && !empty($name)) {
                $params = array("Command" => "LogsHandHistory",
                    "Date" => $date,
                    "Name" => $name
                );
                $api = $this->getDI()->getApi()->poker($params);

                if ($api->Result == "Ok") {
                    $this->view->events = $api->Data;
                } else {
                    $this->view->error = $api->Error;
                }
            }
        }
        // Pass all
        $params = array("Command" => "LogsHandHistory",
        );
        $api = $this->getDI()->getApi()->poker($params);
        $outDate = array();
        $outName = array();
        foreach ($api->Date as $key => $value)
            $outDate[$value] = $value;

        foreach ($api->Name as $key => $value)
            $outName[$value] = $value;

        $this->view->Name = $outName;
        $this->view->Date = $outDate;
    }

    public function logHandCacheAction()
    {
        if ($this->request->isPost()) {

            // Get the parameter

            $hand = $this->request->getPost('hand');
            if (!empty($hand)) {
                $params = array("Command" => "LogsHandHistory",
                    "Hand" => $hand,
                );
                $api = $this->getDI()->getApi()->poker($params);

                if ($api->Result == "Ok") {
                    $this->view->events = $api->Data;
                } else {
                    $this->view->error = $api->Error;
                }
            }
        }
    }

    public function ringDetailsAction()
    {
        if ($this->request->isPost()) {

            // Get the parameter

            $name = $this->request->getPost('name');
            if (!empty($name)) {
                $params = array("Command" => "RingGamesPlaying",
                    "Name" => $name
                );
                $apiFirst = $this->getDI()->getApi()->poker($params);

                $params = array("Command" => "RingGamesGet",
                    "Name" => $name
                );
                $apiSecond = $this->getDI()->getApi()->poker($params);


                $params = array("Command" => "RingGamesWaiting",
                    "Name" => $name
                );
                $apiThird = $this->getDI()->getApi()->poker($params);

                if ($apiFirst->Result == "Ok" && $apiSecond->Result == "Ok" && $apiThird->Result == "Ok") {
                    $this->view->ring = $apiSecond;
                    $this->view->waiting = $apiThird;
                    $this->view->playing = $apiFirst;
                } else {
                    $this->view->ring = "Error Occurred";
                    $this->view->waiting = "Error Occurred";
                    $this->view->playing = "Error Occurred";
                }
            }
        }
        // Pass all
        $params = array("Command" => "RingGamesList",
            "Fields" => "Name"
        );
        $api = $this->getDI()->getApi()->poker($params);
        $out = array();
        foreach ($api->Name as $key => $value)
            $out[$value] = $value;

        $this->view->Rings = $out;
    }

    public function tournamentDetailsAction()
    {
        if ($this->request->isPost()) {

            $name = $this->request->getPost('name');
            if (!empty($name)) {
                $params = array("Command" => "TournamentsPlaying",
                    "Name" => $name
                );
                $apiFirst = $this->getDI()->getApi()->poker($params);

                $params = array("Command" => "TournamentsGet",
                    "Name" => $name
                );
                $apiSecond = $this->getDI()->getApi()->poker($params);


                $params = array("Command" => "TournamentsWaiting",
                    "Name" => $name
                );
                $apiThird = $this->getDI()->getApi()->poker($params);

                if ($apiFirst->Result == "Ok" && $apiSecond->Result == "Ok" && $apiThird->Result == "Ok") {
                    $this->view->tournament = $apiSecond;
                    $this->view->waiting = $apiThird;
                    $this->view->playing = $apiFirst;
                } else {
                    $this->view->ring = "Error Occurred";
                    $this->view->waiting = "Error Occurred";
                    $this->view->playing = "Error Occurred";
                }
            }
        }
        // Pass all
        $params = array("Command" => "TournamentsList",
            "Fields" => "Name"
        );
        $api = $this->getDI()->getApi()->poker($params);
        $out = array();
        foreach ($api->Name as $key => $value)
            $out[$value] = $value;

        $this->view->Tournaments = $out;
    }

    public function tournamentResultAction()
    {
        if ($this->request->isPost()) {

            $name = $this->request->getPost('name');
            $date = $this->request->getPost('date');
            if (!empty($date) && !empty($name)) {
                $params = array("Command" => "TournamentsResults",
                    "Name" => $name,
                    "Date" => $date,
                );
                $api = $this->getDI()->getApi()->poker($params);

                $this->view->tournament = $api;
            }
        }
        // Pass all
        $params = array("Command" => "TournamentsResults",
            "Fields" => "Name"
        );
        $api = $this->getDI()->getApi()->poker($params);
        $outName = array();
        $outDate = array();
        foreach ($api->Name as $key => $value)
            $outName[$value] = $value;

        foreach ($api->Date as $key => $value)
            $outDate[$value] = $value;

        $this->view->Name = $outName;
        $this->view->Date = $outDate;

    }


    public function loginsAction()
    {
        $ip = $this->request->getPost('ip');
        $parameters = array('order' => 'createdAt DESC');
        if (!empty($ip)) {
            $parameters = array(
                "conditions" => "ipAddress = '" . $ip . "'",
            );
        }
        $ips = SuccessLogins::find($parameters);
        $this->view->ips = $ips;
    }


    public function balanceAction()
    {
        $usersId = $this->request->getPost('usersId');
        if (!empty($usersId)) {
            $user = Users::findFirstById($usersId);
            $params = array("Command" => "AccountsGet",
                "Player" => $user->player,
            );
            $api = $this->getDI()->getApi()->poker($params);
        } else {
            $params = array("Command" => "AccountsList",
                "Fields" => "Player,Balance,RingChips,RegChips"
            );
            $api = $this->getDI()->getApi()->poker($params);
        }

        $this->view->balances = $api;
        $this->view->users = Users::find();
    }


    /**
     * Searches for status
     */
    public function statusAction()
    {
        $params = array("Command" => "SystemStats",
        );
        $api = $this->getDI()->getApi()->poker($params);
        $this->view->Stats = $api;
        $parameters = array(
            "conditions" => "status = 'No'",
        );
        $pendingCashouts = Cashouts::count($parameters);
        $this->view->pendingCashouts = $pendingCashouts;
        $parameters = array(
            "conditions" => "toStatus = 'unread' AND type = 'request'",
        );
        $pendingMessages = Support::count($parameters);
        $this->view->pendingMessages = $pendingMessages;
    }

    public function connectionsAction()
    {
        $params = array("Command" => "ConnectionsList",
            "Fields" => "SessionID,Status,Player,PC,IP,Connect,Login,LastAction,PacketsIn,PacketsOut"
        );
        $api = $this->getDI()->getApi()->poker($params);
        $this->view->connections = $api;
    }


}